### ISSUE TITLE
Error Code 400

### ISSUE THREAD

**Issue by jbjknt** [UnUniFi/utils#197]
Had this issue on the withdrawl function when I tried to use more gas than the default.

**Comment by YasunoriMATSUOKA** [comment]
@jbjknt 
Thank you for creating the issue.

I guess insufficient fee caused the issue. I can send transaction to withdraw collateral more gas than the default.

Default gas price = 0.015 and then withdraw collateral tx fee will be about 4000 to 5000 uguu.
The gas price max value enabled in the form's slider = 1 and then withdraw collateral tx fee will be about 260000 to 270000 uguu. If you don't have the enough balances, error will occur. It is not user friendly now, but it is expected behavior.

But if you have enough balances and the issue is reproduced, If you can provide us with the following information, it will be very helpful for us to investigate the problem.

1. Your address
1. What URL node (web app) did you use?
  - http://a.test.ununifi.cauchye.net
  - http://b.test.ununifi.cauchye.net 
2. When you had the issue, how many minimum gas price did you set?
3. Screenshot of error
4. (If you can, Information displayed in the Console and Network of the browser's developer tools)

Thank you for your cooperation.

**Comment by YasunoriMATSUOKA** [comment]
No response, so I will close it.
If you have any questions, please contact us again.
